[package]
name = "mysite"
version = "0.1.0"
authors = ["zhenhuanlee <zhenhuanlee@outlook.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
